### ISSUE TITLE
Invalid token on brand new bot.

### ISSUE THREAD

**Issue by djassoRaph** [Tkaixiang/Storeman-Bot#151]
Hello. I've done all the installations and requested elements. 
Lots of surpises along the way. Learning as I go. 

Here's the log of my docker file.

I'm on windows unfortunately. 

```
C:\Users\Admin\Desktop\Storeman-Bot> docker compose logs bot
storeman-bot-bot-1  | Item List CSV file successfully processed
storeman-bot-bot-1  | Location CSV file successfully processed       
storeman-bot-bot-1  | Connecting to MongoDB at mongodb://mongo:27017/
storeman-bot-bot-1  | HTTP server now listening at http://0.0.0.0:8090
storeman-bot-bot-1  | /app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:134
storeman-bot-bot-1  |     const invalidToken = new Error(ErrorCodes.TokenInvalid);
storeman-bot-bot-1  |                          ^
storeman-bot-bot-1  | 
storeman-bot-bot-1  | Error [TokenInvalid]: An invalid token was provided.
storeman-bot-bot-1  |     at WebSocketManager.connect (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:134:26)
storeman-bot-bot-1  |     at Client.login (/app/node_modules/discord.js/src/client/Client.js:232:21)
storeman-bot-bot-1  |     at /app/index.js:530:16
storeman-bot-bot-1  |     at Generator.next (<anonymous>)
storeman-bot-bot-1  |     at fulfilled (/app/index.js:5:58)
storeman-bot-bot-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
storeman-bot-bot-1  |   code: 'TokenInvalid'
storeman-bot-bot-1  | }
storeman-bot-bot-1  | Item List CSV file successfully processed
storeman-bot-bot-1  | Location CSV file successfully processed
storeman-bot-bot-1  | Connecting to MongoDB at mongodb://mongo:27017/
storeman-bot-bot-1  | MongoDB connected successfully!
storeman-bot-bot-1  | HTTP server now listening at http://0.0.0.0:8090
storeman-bot-bot-1  | /app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:134
storeman-bot-bot-1  |     const invalidToken = new Error(ErrorCodes.TokenInvalid);
storeman-bot-bot-1  |                          ^
storeman-bot-bot-1  |
storeman-bot-bot-1  | Error [TokenInvalid]: An invalid token was provided.
storeman-bot-bot-1  |     at WebSocketManager.connect (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:134:26)
storeman-bot-bot-1  |     at Client.login (/app/node_modules/discord.js/src/client/Client.js:232:21)
storeman-bot-bot-1  |     at /app/index.js:530:16
storeman-bot-bot-1  |     at Generator.next (<anonymous>)
storeman-bot-bot-1  |     at fulfilled (/app/index.js:5:58)
storeman-bot-bot-1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
storeman-bot-bot-1  |   code: 'TokenInvalid'
storeman-bot-bot-1  | }
```

I really don't know what to do. I thought I had the right token. In the right .env file. 

```
STOCKPILER_TOKEN=123457 <= My token taken from discord 
NODE_ENV=production
STOCKPILER_CLIENT_ID=#BOT NAME#NumberTag" <= My bot number and name taken from  https://discord.com/developers/applications/ page
STOCKPILER_MULTI_SERVER=false
```

I'm going to check if it's not my firewall that's blocking. But I doubt it. I'll keep you posted. 

If you can hlep me that would be fantastic.

Thank you in advance for reading.
kind regards

Raphael.

**Comment by djassoRaph** [comment]
Oh I think I got it.  It's just that I had inserted the wrong STOCKPILER_TOKEN. 

Rather explicit error of course.

MTAzMDkxNjY4NDc3MDQ0NzQ3MA.G6ddiB.oRqvtL1jAhTZfIlIEAbz2fDC0u3tJcqDqOX3aI

But if you would like to improve your documentation, perhaps include an example of what the token "could look like" in your stuff.. Thats it. :D Thank you for your great work.

**Comment by Tkaixiang** [comment]
Noted :). I have updated it in the wikipedia page
