### ISSUE TITLE
channel.isTextBased is not a function

### ISSUE THREAD

**Issue by KaruleanDEV** [Tkaixiang/Storeman-Bot#190]
` /app/node_modules/discord.js/src/client/actions/InteractionCreate.js:46
       if (channel && !channel.isTextBased()) return;
                               ^

 TypeError: channel.isTextBased is not a function
at InteractionCreateAction.handle (/app/node_modules/discord.js/src/client/actions/InteractionCreate.js:46:33)
at module.exports [as INTERACTION_CREATE] (/app/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)
at WebSocketManager.handlePacket (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:352:31)
at WebSocketShard.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:480:22)
at WebSocketShard.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketShard.js:320:10) 
at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:199:18)
at WebSocket.emit (node:events:513:28)
at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:1178:20)
at Receiver.emit (node:events:513:28)
at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:528:14)`

**Comment by KaruleanDEV** [comment]
Please update discord.js in your docker image to the latest version to fix this. 
https://github.com/discordjs/discord.js/issues/9295

**Comment by Tkaixiang** [comment]
Sorry for the really late reply, this has been fixed in 1a063ea
