### ISSUE TITLE
Error when setting role perms

### ISSUE THREAD

**Issue by al-arz** [Tkaixiang/Storeman-Bot#212]
Been adding admin perms to certain roles.
First role added successfully, second one broke it.

```
An error has occurred in Storeman Bot for the command sprole

...
{"stack":"TypeError: Cannot read properties of undefined (reading 'length')\n    at /app/Commands/sprole.js:40:64\n    at Generator.next (<anonymous>)\n    at fulfilled (/app/Commands/sprole.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"Cannot read properties of undefined (reading 'length')"}
```

Note: roles that I've been adding have spaces and cyrillic characters.

**Comment by Tkaixiang** [comment]
Fixed in 849c59faebc377a86b73307731b9b4d1ee96cc24
thanks for reporting
